services:
    _defaults:
        autowire: true
        autoconfigure: true

    ATSearchBundle\CacheWarmer\:
        resource: '../../CacheWarmer/'

    ATSearchBundle\Command\:
        resource: '../../Command/'

    ATSearchBundle\Doctrine\Converter\:
        resource: '../../Doctrine/Converter/'

    ATSearchBundle\Doctrine\Service\:
        resource: '../../Doctrine/Service/'

    ATSearchBundle\Service\:
        resource: '../../Service/'
