services:
    _defaults:
        autowire: true
        autoconfigure: true

    ATSearchBundle\:
        resource: '../../'
        exclude: '../../{DependencyInjection,Resources,Query,Exception,Enum,Search/ValueObject}'
